#!/bin/bash

apps=("sm" "em" "ih")
locs=("ru_RU" "en_US" "es_ES" "pt_PT")
versions=("v1")

rm -rf output

for app in ${apps[@]}; do
    for loc in ${locs[@]}; do
        for version in ${versions[@]}; do
            rm .env

            touch .env

            echo "VUE_APP_NAME=$app">>.env
            echo "VUE_APP_LANG=$loc">>.env
            echo "VUE_APP_VERSION=$version">>.env

            npm run build

            if [ ! -d "output" ]; then
                mkdir output
            fi

            cp -R app/*.html output/
        done
    done
done